# Generated by Django 6.0.5 on 2026-05-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_booking_passenger_email_booking_pnr_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pnr_number',
            field=models.CharField(default='FCDF606C', max_length=10, unique=True),
        ),
    ]
