# Generated by Django 6.0.5 on 2026-05-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_booking_pnr_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_ticket_number', models.CharField(max_length=50)),
                ('airline_name', models.CharField(max_length=100)),
                ('pnr_number', models.CharField(max_length=10)),
                ('exchange_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('new_departure_city', models.CharField(max_length=100)),
                ('new_arrival_city', models.CharField(max_length=100)),
                ('new_departure_date', models.DateField()),
                ('new_return_date', models.DateField(blank=True, null=True)),
                ('exchange_reason', models.TextField()),
                ('exchange_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='pnr_number',
            field=models.CharField(default='3F08A205', max_length=10, unique=True),
        ),
    ]
