# Generated by Django 6.0.5 on 2026-05-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_ticketexchange_alter_booking_pnr_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=50)),
                ('airline_name', models.CharField(max_length=100)),
                ('pnr_number', models.CharField(max_length=10)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund_status', models.CharField(max_length=50)),
                ('refund_method', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=200)),
                ('refund_reason', models.TextField()),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='pnr_number',
            field=models.CharField(default='7710EEFA', max_length=10, unique=True),
        ),
    ]
