# Generated by Django 6.0.5 on 2026-05-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_ticketrefund_alter_booking_pnr_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pnr_number',
            field=models.CharField(default='44A313B9', max_length=10, unique=True),
        ),
    ]
