# Generated by Django 6.0.5 on 2026-05-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_booking_pnr_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_ticket_number', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=200)),
                ('airline_name', models.CharField(max_length=100)),
                ('credit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('customer_email', models.EmailField(max_length=254)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='pnr_number',
            field=models.CharField(default='B8B7038D', max_length=10, unique=True),
        ),
    ]
