# Generated by Django 6.0.5 on 2026-05-31 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_booking_airline_name_booking_arrival_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pnr_number',
            field=models.CharField(default='E7586F09', max_length=10, unique=True),
        ),
    ]
