<<<<<<< HEAD
# Generated by Django 6.0.5 on 2026-05-31 22:24
=======
# Generated by Django 6.0.5 on 2026-05-29 01:31
>>>>>>> 3999f0cc3fb63e0ac6f33cacd02393146848ee55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('crm', '0008_booking_airline_name_booking_arrival_city_and_more'),
=======
        ('crm', '0008_booking_agent_futurecredit_agent_and_more'),
>>>>>>> 3999f0cc3fb63e0ac6f33cacd02393146848ee55
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pnr_number',
<<<<<<< HEAD
            field=models.CharField(default='E7586F09', max_length=10, unique=True),
=======
            field=models.CharField(default='CF0505BF', max_length=10, unique=True),
>>>>>>> 3999f0cc3fb63e0ac6f33cacd02393146848ee55
        ),
    ]
