# Generated by Django 6.0.5 on 2026-05-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_booking_agent_futurecredit_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pnr_number',
            field=models.CharField(default='CF0505BF', max_length=10, unique=True),
        ),
    ]
