# Generated by Django 6.0.5 on 2026-06-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_booking_pnr_number_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pnr_number',
            field=models.CharField(default='9B031540', max_length=10, unique=True),
        ),
    ]
