<<<<<<< HEAD
# Generated by Django 6.0.5 on 2026-06-04 14:23
=======
# Generated by Django 6.0.5 on 2026-06-03 08:48
>>>>>>> 3999f0cc3fb63e0ac6f33cacd02393146848ee55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('crm', '0010_booking_billing_address_booking_card_holder_name_and_more'),
=======
        ('crm', '0010_alter_booking_pnr_number_message'),
>>>>>>> 3999f0cc3fb63e0ac6f33cacd02393146848ee55
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pnr_number',
<<<<<<< HEAD
            field=models.CharField(default='0A6A17E9', max_length=10, unique=True),
=======
            field=models.CharField(default='9B031540', max_length=10, unique=True),
>>>>>>> 3999f0cc3fb63e0ac6f33cacd02393146848ee55
        ),
    ]
