# Generated by Django 6.0.5 on 2026-06-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_booking_billing_address_booking_card_holder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pnr_number',
            field=models.CharField(default='0A6A17E9', max_length=10, unique=True),
        ),
    ]
