# Generated by Django 6.0.5 on 2026-06-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_booking_pnr_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pnr_number',
            field=models.CharField(default='EFC87D04', max_length=10, unique=True),
        ),
    ]
