<<<<<<< HEAD
# Generated by Django 6.0.5 on 2026-06-05 13:00
=======
# Generated by Django 6.0.5 on 2026-06-03 09:17
>>>>>>> 3999f0cc3fb63e0ac6f33cacd02393146848ee55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_booking_pnr_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pnr_number',
<<<<<<< HEAD
            field=models.CharField(default='EFC87D04', max_length=10, unique=True),
=======
            field=models.CharField(default='565B1A67', max_length=10, unique=True),
>>>>>>> 3999f0cc3fb63e0ac6f33cacd02393146848ee55
        ),
    ]
