# Generated by Django 6.0.3 on 2026-06-11 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_booking_airline_name_booking_arrival_city_and_more'),
        ('crm', '0010_booking_billing_address_booking_card_holder_name_and_more'),
        ('crm', '0012_alter_booking_pnr_number'),
    ]

    operations = [
    ]
