# Generated by Django 6.0.3 on 2026-06-11 17:19

import crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_merge_20260611_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='authorized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_authorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pnr_number',
            field=models.CharField(default=crm.models.generate_pnr, max_length=10, unique=True),
        ),
    ]
